[package]
name = "sdfbox-client"
license = "MIT"
version = "0.1.0"
authors = ["Philpax <me@philpax.me>"]
edition = "2021"
resolver = "2"

[dependencies]
anyhow = "1.0.57"
bevy = "0.7"
bevy_egui = "0.14.0"
bevy_web_fullscreen = { git = "https://github.com/oscrim/bevy_web_fullscreen.git" }
bimap = "0.6.2"
egui_node_graph = { git = "https://github.com/philpax/egui_node_graph.git", branch = "active" }
saft = "0.30.0"
smooth-bevy-cameras = "0.4.0"

shared = { path = "../shared" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "0.2.0"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.57"
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
